In [3]:
import pandas as pd

In [5]:
import numpy as np

In [7]:
data=np.random.randn(4,3)

In [11]:
data

array([[ 2.51314972,  1.43642509,  0.90057807],
       [ 0.14260263,  0.36222747, -0.03944065],
       [ 1.83647359,  1.09013208, -2.86410608],
       [ 2.58318762,  1.86453847,  2.89330309]])

In [21]:
data_frame=pd.DataFrame(data)

In [23]:
type(data_frame)

pandas.core.frame.DataFrame

In [25]:
type(data_frame[0])

pandas.core.series.Series

In [31]:
new_df=pd.DataFrame(data,index=["name1","name2","name3","name4"],columns=["SAlary","Age","Seniority"])

In [34]:
new_df

         SAlary       Age  Seniority
name1  2.513150  1.436425   0.900578
name2  0.142603  0.362227  -0.039441
name3  1.836474  1.090132  -2.864106
name4  2.583188  1.864538   2.893303

In [36]:
new_df["SAlary"]

name1    2.513150
name2    0.142603
name3    1.836474
name4    2.583188
Name: SAlary, dtype: float64

In [40]:
new_df[["Age","SAlary"]]

            Age    SAlary
name1  1.436425  2.513150
name2  0.362227  0.142603
name3  1.090132  1.836474
name4  1.864538  2.583188

In [42]:
new_df.loc["name1"]

SAlary       2.513150
Age          1.436425
Seniority    0.900578
Name: name1, dtype: float64

In [44]:
new_df.loc["name2"]

SAlary       0.142603
Age          0.362227
Seniority   -0.039441
Name: name2, dtype: float64

In [46]:
new_df.iloc[0]

SAlary       2.513150
Age          1.436425
Seniority    0.900578
Name: name1, dtype: float64